### ISSUE TITLE
Compilation errors with current version of Deno

### ISSUE THREAD

**Issue by grempe** [cybertim/SmallSQLiteORM#2]
Running the example code from the readme as `example.ts` fails with the following errors:

```txt
❯ deno run example.ts
Check file:///Users/glenn/tmp/small-orm-sqlite/example.ts
error: TS2345 [ERROR]: Argument of type 'unknown' is not assignable to parameter of type 'string'.
                data.push(col);
                          ~~~
    at file:///Users/glenn/tmp/small-orm-sqlite/lib/SmallSQLite.ts:81:27

TS2339 [ERROR]: Property 'columns' does not exist on type 'Row[]'.
            try { names = rows.columns().map((item) => item.name); } catch (e) {
                               ~~~~~~~
    at file:///Users/glenn/tmp/small-orm-sqlite/lib/SmallSQLite.ts:171:32

TS7006 [ERROR]: Parameter 'item' implicitly has an 'any' type.
            try { names = rows.columns().map((item) => item.name); } catch (e) {
                                              ~~~~
    at file:///Users/glenn/tmp/small-orm-sqlite/lib/SmallSQLite.ts:171:47

TS2339 [ERROR]: Property 'next' does not exist on type 'Row[]'.
            return { count: <number>rows.next().value[0], objects: [] };
                                         ~~~~
    at file:///Users/glenn/tmp/small-orm-sqlite/lib/SmallSQLite.ts:183:42

Found 4 errors.
```

```txt
❯ deno --version
deno 1.20.3 (release, x86_64-apple-darwin)
v8 10.0.139.6
typescript 4.6.2
```

**Comment by enimatek-nl** [comment]
fixed in https://github.com/enimatek-nl/small-orm-sqlite/releases/tag/0.2.1

**Comment by grempe** [comment]
Perhaps you'd like to leave this issue open? The 'fix' was to pin to a version of sqlite that is 9 versions out of date.

**Comment by enimatek-nl** [comment]
I don't disagree, but the whole lib wasn't working anymore, this 'fix' made it work again. 
A feature or enhancement would be to have 3.0 sqlite (lib) support: https://github.com/enimatek-nl/small-orm-sqlite/issues/3
